# .nosana-ci.yml
global:
  image: nosana/solana
  trigger:
    push:
      branches:
        - "*"

jobs:
  - name: build
    commands:
        - npm ci
        - npm run build:program-rust
    artifacts:
      - name: dist
      - name: node_modules

  - name: test
    commands:
      - echo "testing..."
      - npm run test:program-rust
    resources:
      - name: dist
      - name: node_modules

  - name: deploy
    commands:
      - solana-keygen new --no-bip39-passphrase
      - solana airdrop 1 --url devnet
      - solana program deploy dist/program/helloworld.so --url devnet
    resources:
      - name: node_modules
      - name: dist
  